import CustomerList from "@/components/web-pages/customer-list";
import { Metadata } from "next";
import React from "react";

const page = () => {
  return (
    <section>
      <CustomerList />
    </section>
  );
};

export default page;
export const metadata: Metadata = {
  title: "Customer List | Westfert Fertilisers",
  description: "Generated by create next app",
};