import RawMaterial from "@/components/web-pages/raw-material";
import { Metadata } from "next";
import React from "react";

const page = () => {
  return (
    <section>
      <RawMaterial />
    </section>
  );
};

export default page;

export const metadata: Metadata = {
  title: "Raw Material | Westfert Fertilisers",
  description: "Generated by create next app",
};