import StandardRecipes from "@/components/web-pages/standard-recipes";
import { Metadata } from "next";
import React from "react";

const page = () => {
  return (
    <section>
      <StandardRecipes />
    </section>
  );
};

export default page;

export const metadata: Metadata = {
  title: "Standard Recipes | Westfert Fertilisers",
  description: "Generated by create next app",
};