import { Metadata } from 'next';
import React from 'react'

const page = () => {
  return (
    <div>quote-history</div>
  )
}

export default page

export const metadata: Metadata = {
  title: "Quote-history | Westfert Fertilisers",
  description: "Generated by create next app",
};