import AboutWestfert from "@/components/web-pages/settings/about-westfert";
import { Metadata } from "next";
import React from "react";

const page = () => {
  return (
    <section>
      <AboutWestfert />
    </section>
  );
};

export default page;

export const metadata: Metadata = {
  title: "About Westfert | Westfert Fertilisers",
  description: "Generated by create next app",
};