import StaffListPage from "@/components/web-pages/staff-list-page";
import { Metadata } from "next";
import React from "react";

const page = () => {
  return <div>
    <StaffListPage />
  </div>;
};

export default page;

export const metadata: Metadata = {
  title: "Staff List | Westfert Fertilisers",
  description: "Generated by create next app",
};